space: space.o events.o render.o raster.o model.o input.o clear_qk.o
	cc68x -g space.o events.o render.o raster.o model.o input.o clear_qk.o -o space.prg

space.o: space.c space.h 
	cc68x -g -c space.c 

render.o: render.c render.h
	cc68x -g -c render.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

events.o: events.c events.h
	cc68x -g -c events.c

input.o: input.c input.h
	cc68x -g -c input.c

model.o: model.c model.h
	cc68x -g -c model.c

clear_qk.o: clear_qk.s
	gen -D -L2 clear_qk.s

clean:
	$(RM) *.o *.prg 
