space: space.o events.o render.o raster.o model.o input.o psg.o music.o effects.o clear_qk.o vid_base.o
	cc68x -g space.o events.o render.o raster.o model.o input.o psg.o music.o effects.o clear_qk.o vid_base.o -o space.prg

space.o: space.c space.h 
	cc68x -g -c space.c 

render.o: render.c render.h
	cc68x -g -c render.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

events.o: events.c events.h
	cc68x -g -c events.c

input.o: input.c input.h
	cc68x -g -c input.c

model.o: model.c model.h
	cc68x -g -c model.c

clear_qk.o: clear_qk.s
	gen -D -L2 clear_qk.s

psg.o: psg.c psg.h
	cc68x -g -c psg.c

music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

vid_base.o: vid_base.s
	gen -D -L2 vid_base.s

# This is the make for the PSG sound test driver
tst_s7: driver.o psg.o music.o effects.o
	cc68x -g driver.o psg.o music.o effects.o -o tst_s7.prg

driver.o: driver.c psg.h music.h effects.h
	cc68x -g -c driver.c

clean:
	$(RM) *.o *.prg 
	