space: space.o events.o render.o raster.o bitmaps.o model.o input.o psg.o music.o effects.o isr.o clear_qk.o isr_asm.o
	cc68x -g space.o events.o render.o raster.o bitmaps.o model.o input.o psg.o music.o effects.o isr.o clear_qk.o isr_asm.o -o space.prg

space.o: space.c space.h 
	cc68x -g -c space.c 

render.o: render.c render.h
	cc68x -g -c render.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

events.o: events.c events.h
	cc68x -g -c events.c

input.o: input.c input.h
	cc68x -g -c input.c

model.o: model.c model.h
	cc68x -g -c model.c

clear_qk.o: clear_qk.s
	gen -D -L2 clear_qk.s

psg.o: psg.c psg.h
	cc68x -g -c psg.c

music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

isr_asm.o: isr_asm.s
	gen -D -L2 isr_asm.s

isr.o: isr.c isr.h
	cc68x -g -c isr.c

clean:
	$(RM) *.o *.prg 

	